[tool.poetry]
name = "python-proj-1-test"
version = "0.1.0"
description = "test project 1"
authors = ["Kenneth Man <kenneth.man@ntegra.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
